# Generated by Django 3.0.2 on 2020-01-23 16:22

from django.db import migrations, models
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200123_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/no_img.png', null=True, upload_to=product.utils.upload_image_path),
        ),
    ]
