# Generated by Django 3.0.2 on 2020-01-24 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200123_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
