# Generated by Django 3.0.2 on 2020-01-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchtags',
            options={'verbose_name_plural': 'Search Tags'},
        ),
    ]
